git_source(:github) { |name| "https://github.com/#{name}.git" }
# frozen_string_literal: true
source "https://rubygems.org"

# If you modify this file, you'll need to build a new version of the
# docs-builder Docker image to keep things speedy in CI. See ci/README.md for
# instructions.

# Removed `gem "jekyll", "~> 4.3"`` until conflict with our use of ianjevins/jekyll-remote-include is resolved (DOC-13509)
gem "jekyll", "4.3.4"
gem "liquid-c", "~> 4.0.0"
gem "redcarpet", "~> 3.6"
gem "rss"
gem "webrick"
gem "jekyll-minifier"
gem 'csv'
gem 'logger'
gem 'base64'
gem 'bigdecimal'
gem 'mutex_m'
group :jekyll_plugins do
    gem "jekyll-include-cache"
    gem 'jekyll-algolia', "~> 1.0", path: "./jekyll-algolia-dev"
    gem 'jekyll-remote-include', github: 'ianjevans/jekyll-remote-include', tag: 'v1.1.7'
    gem "jekyll-last-modified-at"
    gem "jekyll-get-json"
    gem 'jekyll-sass-converter', '~> 2.0'
  end
