# TESTING CONFIGURATION - DO NOT USE IN PRODUCTION
# This file contains all test configurations for cache and retry testing

# Phase 1: Cache Testing Only
[build]
  base = "src/current/"
  publish = "_site/"
  command = "./netlify/build-test.sh"
  edge_functions = "./netlify/edge-functions"
  [build.environment]
    NODE_VERSION = "18.14.0"
    RUBY_VERSION = "3.2.1"
    # Enable cache testing
    NETLIFY_CACHE_TEST = "true"
    JEKYLL_REMOTE_INCLUDE_CACHE = "true"
    JEKYLL_REMOTE_INCLUDE_CACHE_TTL = "3600"
  [build.processing.html]
    pretty_urls = true

# Phase 1: Cache Plugin
[[plugins]]
  package = "@netlify/plugin-cache-build"
  [plugins.inputs]
    paths = [
      ".jekyll-cache",
      ".remote-includes-cache", 
      "node_modules/.cache",
      "_data/cached"
    ]
    ttl = 86400  # 24 hours

# Phase 2: Add Retry Plugin (uncomment for retry testing)
# [[plugins]]
#   package = "@netlify/plugin-retry-build"
#   [plugins.inputs]
#     retryConditions = ["TIMEOUT", "NETWORK", "BUILD_FAILED"]
#     maxRetries = 3
#     retryDelay = 30

[[edge_functions]]
  path = "/*"
  function = "blockBytedance"