DirectoryPath: "_site"
ExternalTimeout: 30
IgnoreDirs:
  - ^docs/stable
  - ^docs/dev
  - ^docs/v1.2
IgnoreURLs:
  - http://localhost:4000
  - "https://github.com"
  - "github.com"
IgnoreInternalEmptyHash: true
TestFilesConcurrently: false 
