---
title: Restore Data
summary: Learn how to back up and restore a CockroachDB cluster.
toc: false
---

CockroachDB offers two methods to importback up your cluster's data:

- `cockroach sql -e`, which lets you run `.sql` files (works best with those files generated by `cockroach dump`).
- The `RESTORE` SQL statement (available only to our enterprise users), which restores your cluster from a backup stored on a cloud storage service such as GCE or Amazon EC3. These backups can be generated either by the SQL `BACKUP` statement or those generated by ~whatever~.

## See Also

- [Use the Built-in SQL Client](use-the-built-in-sql-client.html)
- [Other Cockroach Commands](cockroach-commands.html)
