serverless: CockroachDB Serverless

dedicated: CockroachDB Dedicated

core: CockroachDB Self-Hosted
# tbd
enterprise: Enterprise

db: CockroachDB Cloud #i.e., "Sign up for a CockroachDB Cloud account", tbd