serverless: CockroachCloud Serverless (beta)
# to be CockroachCloud Serverless then CockroachDB Serverless (beta)
serverless-plan: CockroachCloud Serverless #i.e. "1. Choose the **CockroachCloud Free** plan."
# to be CockroachCloud Serverless
dedicated: CockroachCloud Dedicated
# to be CockroachDB Managed
core: Core
#stays the same
enterprise: Enterprise
# to be CockroachDB Self-Hosted
db: CockroachCloud #i.e. "Sign up for a CockroachCloud account"
# to be CockroachDB