version: '2.1'

networks:
  shared:
    driver: bridge
  dc0:
    driver: bridge
  dc1:
    driver: bridge
  dc2:
    driver: bridge

services:

  # DC 0 nodes

  roach-0:
    container_name: roach-0
    hostname: roach-0
    image: cockroachdb/cockroach:${COCKROACH_VERSION:-v2.0.0}
    networks:
      - shared
      - dc0
    command: start --logtostderr --insecure --locality=datacenter=dc-0 --join=roach-0,roach-1,roach-2
    ports:
      - 8080:8080
      - 26257:26257

  roach-1:
    container_name: roach-1
    hostname: roach-1
    image: cockroachdb/cockroach:${COCKROACH_VERSION:-v2.0.0}
    networks:
      - shared
      - dc0
    command: start --logtostderr --insecure --locality=datacenter=dc-0 --join=roach-0,roach-1,roach-2
    ports:
      - 8081:8080
      - 26258:26257

  # DC 1 nodes

  roach-2:
    container_name: roach-2
    hostname: roach-2
    image: cockroachdb/cockroach:${COCKROACH_VERSION:-v2.0.0}
    networks:
      - shared
      - dc1
    command: start --logtostderr --insecure --locality=datacenter=dc-1 --join=roach-0,roach-1,roach-2
    ports:
      - 8082:8080
      - 26259:26257

  roach-3:
    container_name: roach-3
    hostname: roach-3
    image: cockroachdb/cockroach:${COCKROACH_VERSION:-v2.0.0}
    networks:
      - shared
      - dc1
    command: start --logtostderr --insecure --locality=datacenter=dc-1 --join=roach-0,roach-1,roach-2
    ports:
      - 8083:8080
      - 26260:26257

  # DC 2 nodes

  roach-4:
    container_name: roach-4
    hostname: roach-4
    image: cockroachdb/cockroach:${COCKROACH_VERSION:-v2.0.0}
    networks:
      - shared
      - dc2
    command: start --logtostderr --insecure --locality=datacenter=dc-2 --join=roach-0,roach-1,roach-2
    ports:
      - 8084:8080
      - 26261:26257

  roach-5:
    container_name: roach-5
    hostname: roach-5
    image: cockroachdb/cockroach:${COCKROACH_VERSION:-v2.0.0}
    networks:
      - shared
      - dc2
    command: start --logtostderr --insecure --locality=datacenter=dc-2 --join=roach-0,roach-1,roach-2
    ports:
      - 8085:8080
      - 26262:26257
