extends: substitution
message: Use '%s' instead of '%s'
ignorecase: false
level: error
nonword: true
swap:
  '\beg\b': e.g.,
  '\bie\b': i.e.,
  'e\.g\.(?:[^,]|$)': e.g.,
  'i\.e\.(?:[^,]|$)': i.e.,
  '\betc\b[^\.]': etc.
