extends: substitution
message: Use '%s' over '%s'
ignorecase: false
level: error
swap:
  'New in v\d{1,2}\.\d': '{% include_cached new-in.html version="vXX.Y" %}'
  'Changed in v\d{1,2}\.\d': '{% include_cached new-in.html version="vXX.Y" %}'
