baseurl: /docs/api
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "tutorial"
destination: _site/docs/api
exclude:
- __tests__
- build
- scripts
- vendor
- archived
- package.json
- package-lock.json
- build-netlify.sh
include:
- _redirects
jekyll-minifier:
  compress_css: 'false'
  compress_javascript: 'true'
  compress_js_templates: 'false'
  compress_json: 'true'
  exclude:
  - '**.html'
  - js/rapidoc-min.js
  preserve_line_breaks: 'false'
  preserve_php: 'true'
  remove_comments: 'true'
  remove_form_attributes: 'false'
  remove_http_protocol: 'false'
  remove_https_protocol: 'false'
  remove_input_attributes: 'false'
  remove_intertag_spaces: 'false'
  remove_javascript_protocol: 'false'
  remove_link_attributes: 'false'
  remove_multi_spaces: 'false'
  remove_quotes: 'false'
  remove_script_attributes: 'false'
  remove_spaces_inside_tags: 'false'
  remove_style_attributes: 'false'
  simple_boolean_attributes: 'false'
  simple_doctype: 'false'
  uglifier_args:
    harmony: 'true'
jekyll_get_json:
- data: cloud_api_releases
  json: https://cockroachlabs.cloud/assets/docs/api/manifest.json
main_url: https://www.cockroachlabs.com
plugins:
- jekyll-include-cache
- jekyll-last-modified-at
- jekyll-minifier
- jekyll-get-json
site_title: CockroachDB Docs
