[build]
  base = "src/api/"
  publish = "_site/"
  command = "./build-netlify.sh"
  [build.environment]
    NODE_VERSION = "18.14.0"
    RUBY_VERSION = "3.2.1"
  [build.processing]
    skip_processing = false
  [build.processing.css]
    bundle = false
    minify = false
  [build.processing.js]
    bundle = false
    minify = false
  [build.processing.html]
    pretty_urls = true
  [build.processing.images]
    compress = false

#[[plugins]]
#  package = "@netlify/plugin-lighthouse"
#  [plugins.inputs]
#    output_path = "./reports/lighthouse.html"
#    [[plugins.inputs.audits]]
#      path = "./docs/index.html"
