#!/usr/bin/env bash

set -euo pipefail

image=cockroachdb/docs-builder
version=${COCKROACH_DOCS_BUILDER_VERSION:-20180116-110443}

root=$(cd "$(dirname "$0")" && pwd)
repo_root=$root/..

usage_and_exit() {
  echo "usage: $0 <run|build|push>" >&2
  exit 1
}

command=${1:-} && shift
[[ "$command" ]] || usage_and_exit

case "$command" in
  build)
    docker build --tag="$image" --file="$root/Dockerfile" "$repo_root"
    ;;
  push)
    tag=$(date +%Y%m%d-%H%M%S)
    docker tag "$image" "$image:$tag"
    docker push "$image:$tag"
    ;;
  run)
    [[ -t 0 ]] && tty=--tty
    docker run --rm --interactive ${tty:-} \
      --user "$(id -u):$(id -g)" \
      --env AWS_ACCESS_KEY_ID \
      --env AWS_SECRET_ACCESS_KEY \
      --volume="$repo_root:/docs" \
      "$image:$version" "$@"
    ;;
  *)
    usage_and_exit
    ;;
esac
