#!/usr/bin/env bash

set -euo pipefail

root="$(dirname "$0")"

# run runs a command in the builder container.
run() {
  echo "$@"
  "$root/builder" run "$@"
}

# Tell the Makefile we've already installed dependencies.
touch "$root/../bootstrap"
touch "$root/../vendor"

run make standard-build managed-build
