#!/bin/bash

function build {
	bundle exec jekyll build --trace --config _config_base.yml,$1
}

gem install bundler
bundle install
build _config_cockroachdb.yml
build _config_cockroachcloud.yml

cp _site/docs/_redirects _site/_redirects
cat _site/docs/cockroachcloud/_redirects >> _site/_redirects

# Run Algolia if building master
if [[ "$CONTEXT" = "production" ]]; then
	echo "Building Algolia index..."
	ALGOLIA_API_KEY=$PROD_ALGOLIA_API_KEY bundle exec jekyll algolia --config _config_base.yml --builds-config _config_cockroachdb.yml,_config_cockroachcloud.yml
fi;
