#!/bin/bash

function build {
	bundle exec jekyll build --trace --config _config_base.yml,$1
	if [[ $? != 0 ]]; then
	  exit 1
	fi;
}

# Transform API spec for API docs generation
pushd api/
npx swagger2openapi api-spec.json > spec_30.json
npx snippet-enricher-cli --targets="shell_curl" --input=spec_30.json > spec_30_enriched.json
rm spec_30.json
popd

gem install bundler --silent
bundle install --quiet
build _config_cockroachdb.yml

cp _site/docs/_redirects _site/_redirects
cp _site/docs/404.html _site/404.html

# Set up htmltest

echo "GOPATH: ${GOPATH}"

go get -u github.com/wjdp/htmltest > /dev/null
pushd $GOPATH/src/github.com/wjdp/htmltest && ./build.sh>/dev/null 2>&1 && popd

# Run htmltest to check external links on scheduled nightly runs
# (see .github/workflows/nightly.yml)

if [[ "$INCOMING_HOOK_TITLE" = "nightly" ]]; then
	$GOPATH/src/github.com/wjdp/htmltest/bin/htmltest
	if [[ $? != 0 ]]; then
          exit 1
        fi;
fi;

# Run Algolia if building master
if [[ "$CONTEXT" = "production" ]]; then
	echo "Building Algolia index..."
	ALGOLIA_API_KEY=$PROD_ALGOLIA_API_KEY bundle exec jekyll algolia --config _config_base.yml --builds-config _config_cockroachdb.yml
fi;

# Run htmltest, but skip checking external links to speed things up
$GOPATH/src/github.com/wjdp/htmltest/bin/htmltest --skip-external

if [[ $? != 0 ]]; then
  exit 1
fi;

# Run tests defined in __tests__
./node_modules/.bin/jest
exit $?
