serverless: CockroachDB Serverless

dedicated: CockroachDB Dedicated

dedicated-advanced: CockroachDB Dedicated advanced

core: CockroachDB Self-Hosted
# tbd
enterprise: Enterprise

db: CockroachDB Cloud #i.e., "Sign up for a CockroachDB Cloud account", tbd