name: Slack Test V1 Simple

on:
  pull_request:
    types: [review_requested]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Step 2 - With GitHub expression
        run: echo "Team is ${{ github.event.requested_team.slug }}"
